### ISSUE TITLE
wrong category atm?

### ISSUE THREAD

**Issue by FudgeDumbo** [joaoh1/DamageIncorporated#3]
I am not sure if you are going to update it to fabric 1.19
but currently it is categorized in fabric 1.19 
which got me tricked to download and try.
got me good, cuz I went thru the logs several times and found out the version is for quilt only.

**Comment by EnnuiL** [comment]
Uhhh, the new version is classified as for Quilt 1.19 on both CurseForge and Modrinth; If it appeared on a Fabric category, then it was probably an issue with CF?
However, I did forget to update the description in order to reflect the platform switch; That has been fixed
