### ISSUE TITLE
1.19.3 version?

### ISSUE THREAD

**Issue by pulpan977** [joaoh1/DamageIncorporated#6]
Hello,

Will this mod be updated for 1.19.3?

**Comment by EnnuiL** [comment]
Hello! A 1.19.3 port of Damage Incorporated is planned to be worked on, hopefully before this year ends :P

**Comment by EnnuiL** [comment]
Update: unfortunately, Damage Inc. was one of the mods that got heavily impacted by 1.19.3, some deep changes will have to happen in the process; Yep, I'll only manage to get something out on 2023, I can't promise a release before the end of this year

**Comment by EnnuiL** [comment]
Damage Incorporated 3.0.0+1.19.3 is finally out; Hopefully, future updates won't take too long now that the massive internal reorganization has been done
